import time
print("Input 2 numbers to add or subtract together!")
number_1 = (input("Put in your first number: "))
number_2 = (input("Put in your second number: "))
sum_1 = float(number_1) + float(number_2)
print(f"The sum of the numbers is {sum_1}!")
print(input("Press any key to move on forward!"))
print("Input 2 numbers to multiply!")
number_3 = (input("Put in your first number: "))
number_4 = (input("Put in your second number: "))
sum_2 = float(number_3) * float(number_4)
print(f"Your number is {sum_2}!")
print(input("Press any key to continue: "))
quit()